#ifndef CODES_H
#define CODES_H

typedef enum {
  ALLIUM_SUCCESS,
  ALLIUM_FAIL,
  ALLIUM_LEXER_FAIL,
  ALLIUM_PARSER_FAIL,
  ALLIUM_DB_FAIL,
  
  ALLIUM_TABLE_ALREADY_EXISTS_ERR,
  ALLIUM_MAX_TABLES_REACHED_ERR,
  ALLIUM_TABLE_NOT_FOUND_ERR,
  ALLIUM_TABLE_NAME_TOO_LONG_ERR
} AlliumCode;

#endif